at.fhooe.kls.Util Class Reference
Static Public Member Functions
static String toHex (byte[] buf)
static byte[] getRawKey (byte[] seed) throws Exception
static void showToast (Context context, String message)
static byte[] encrypt (byte[] raw, byte[] clear) throws Exception
static byte[] decrypt (byte[] raw, byte[] encrypted) throws Exception
static byte[] toByte (String hexString)
static byte[] generateSeed ()
static String getKey () throws Exception
Detailed Description
The Class Util.
Definition at line 21 of file Util.java.
Member Function Documentation
static byte [] at.fhooe.kls.Util.decrypt (byte[] raw, byte[] encrypted) throws Exception [static]
Decrypt.
Parameters
raw the raw
encrypted the encrypted
Returns
the byte[]
Exceptions
Exception the exception
Definition at line 108 of file Util.java.
Referenced by at.fhooe.kls.SMSAdapter.getKey().
static byte [] at.fhooe.kls.Util.encrypt (byte[] raw, byte[] clear) throws Exception [static]
Encrypt.
Parameters
raw the raw
clear the clear
Returns
the byte[]
Exceptions
Exception the exception
Definition at line 92 of file Util.java.
Referenced by at.fhooe.kls.SMSAdapter.createNote().
static byte [] at.fhooe.kls.Util.generateSeed () [static]
Generate seed.
Returns
the byte[]
Definition at line 135 of file Util.java.
Referenced by at.fhooe.kls.Util.getKey().
static String at.fhooe.kls.Util.getKey () throws Exception [static]
Gets the key.
Returns
the key
Exceptions
Exception the exception
Definition at line 170 of file Util.java.
References at.fhooe.kls.Util.generateSeed(), at.fhooe.kls.Util.getRawKey(), and at.fhooe.kls.Util.toHex().
static byte [] at.fhooe.kls.Util.getRawKey (byte[] seed) throws Exception [static]
Gets the raw key.
Parameters
seed the seed
Returns
the raw key
Exceptions
Exception the exception
Definition at line 62 of file Util.java.
Referenced by at.fhooe.kls.Util.getKey().
static void at.fhooe.kls.Util.showToast (Context context, String message) [static]
Show toast.
Parameters
context the context
message the message
Definition at line 78 of file Util.java.
Referenced by at.fhooe.kls.SecureSMSActivity.onCreate().
static byte [] at.fhooe.kls.Util.toByte (String hexString) [static]
To byte.
Parameters
hexString the hex string
Returns
the byte[]
Definition at line 122 of file Util.java.
Referenced by at.fhooe.kls.SMSAdapter.getKey().
static String at.fhooe.kls.Util.toHex (byte[] buf) [static]
To hex.
Parameters
buf the buf
Returns
the string
Definition at line 32 of file Util.java.
Referenced by at.fhooe.kls.SMSAdapter.createNote(), at.fhooe.kls.Util.getKey(), and at.fhooe.kls.SMSAdapter.open().
The documentation for this class was generated from the following file:
src/at/fhooe/kls/Util.java