at.fhooe.kls.XMPPClient Class Reference
Public Member Functions
boolean login (String _user, String _pass)
synchronized XMPPConnection getConnection ()
void sendMessage (String to, String text)
Roster getRoster ()
boolean isConnected ()
Static Public Member Functions
static synchronized XMPPClient getInstance ()
Detailed Description
The Class XMPPClient.
Definition at line 15 of file XMPPClient.java.
Member Function Documentation
synchronized XMPPConnection at.fhooe.kls.XMPPClient.getConnection ()
Gets the connection.
Returns
the connection
Definition at line 59 of file XMPPClient.java.
Referenced by at.fhooe.kls.Chat.onCreate().
static synchronized XMPPClient at.fhooe.kls.XMPPClient.getInstance () [static]
Gets the single instance of XMPPClient.
Returns
single instance of XMPPClient
Definition at line 69 of file XMPPClient.java.
Referenced by at.fhooe.kls.Chat.onCreate(), and at.fhooe.kls.SecureSMSActivity.onCreate().
Roster at.fhooe.kls.XMPPClient.getRoster ()
Gets the roster.
Returns
the roster
Definition at line 99 of file XMPPClient.java.
Referenced by at.fhooe.kls.SecureSMSActivity.onCreate().
boolean at.fhooe.kls.XMPPClient.isConnected ()
Checks if is connected.
Returns
true, if is connected
Definition at line 108 of file XMPPClient.java.
Referenced by at.fhooe.kls.SecureSMSActivity.onCreate().
boolean at.fhooe.kls.XMPPClient.login (String _user, String _pass)
Login.
Parameters
_user the _user
_pass the _pass
Returns
true, if successful
Definition at line 30 of file XMPPClient.java.
References at.fhooe.kls.XMPPLogic.getInstance(), and at.fhooe.kls.XMPPLogic.setConnection().
void at.fhooe.kls.XMPPClient.sendMessage (String to, String text)
Send message.
Parameters
to the to
text the text
Definition at line 82 of file XMPPClient.java.
The documentation for this class was generated from the following file:
src/at/fhooe/kls/XMPPClient.java