at.fhooe.kls.Hash Class Reference
Static Public Member Functions
static byte[] SHA256 (byte[] text) throws NoSuchAlgorithmException
Static Public Attributes
static final String DIGEST_ALGORITHM = `SHA-256`
Detailed Description
The Class Hash.
Definition at line 9 of file Hash.java.
Member Function Documentation
static byte [] at.fhooe.kls.Hash.SHA256 (byte[] text) throws NoSuchAlgorithmException [static]
Generates a SHA256.
Parameters
text plaintext
Returns
the byte[] hashed plaintext
Exceptions
NoSuchAlgorithmException the no such algorithm exception
Definition at line 20 of file Hash.java.
References at.fhooe.kls.Hash.DIGEST_ALGORITHM.
Referenced by at.fhooe.kls.SMSAdapter.createNote(), at.fhooe.kls.SMSAdapter.getKey(), and at.fhooe.kls.SMSAdapter.open().
Member Data Documentation
final String at.fhooe.kls.Hash.DIGEST_ALGORITHM = `SHA-256` [static]
The Constant DIGEST_ALGORITHM.
Definition at line 11 of file Hash.java.
Referenced by at.fhooe.kls.Hash.SHA256().
The documentation for this class was generated from the following file:
src/at/fhooe/kls/Hash.java