at.fhooe.kls.ContactItem Class Reference
Public Member Functions
String getStatus ()
void setStatus (String status)
String getKey ()
void setKey (String key)
ContactItem (String user)
boolean isAvailable ()
void setAvailable (boolean available)
String getUser ()
void setUser (String user)
int describeContents ()
void writeToParcel (Parcel dest, int flags)
Static Public Attributes
static final
*
Parcelable.Creator
*
< ContactItem > CREATOR
Detailed Description
The Class ContactItem.
Definition at line 10 of file ContactItem.java.
Constructor & Destructor Documentation
at.fhooe.kls.ContactItem.ContactItem (String user)
Instantiates a new contact item.
Parameters
user the user
Definition at line 69 of file ContactItem.java.
Member Function Documentation
String at.fhooe.kls.ContactItem.getKey ()
Gets the key.
Returns
the key
Definition at line 49 of file ContactItem.java.
String at.fhooe.kls.ContactItem.getStatus ()
Gets the status.
Returns
the status
Definition at line 29 of file ContactItem.java.
String at.fhooe.kls.ContactItem.getUser ()
Gets the user.
Returns
the user
Definition at line 101 of file ContactItem.java.
Referenced by at.fhooe.kls.Chat.onCreate().
boolean at.fhooe.kls.ContactItem.isAvailable ()
Checks if is available.
Returns
true, if is available
Definition at line 81 of file ContactItem.java.
void at.fhooe.kls.ContactItem.setAvailable (boolean available)
Sets the available.
Parameters
available the new available
Definition at line 91 of file ContactItem.java.
Referenced by at.fhooe.kls.SecureSMSActivity.onCreate().
void at.fhooe.kls.ContactItem.setKey (String key)
Sets the key.
Parameters
key the new key
Definition at line 59 of file ContactItem.java.
void at.fhooe.kls.ContactItem.setStatus (String status)
Sets the status.
Parameters
status the new status
Definition at line 39 of file ContactItem.java.
Referenced by at.fhooe.kls.SecureSMSActivity.onCreate().
void at.fhooe.kls.ContactItem.setUser (String user)
Sets the user.
Parameters
user the new user
Definition at line 110 of file ContactItem.java.
Member Data Documentation
final Parcelable.Creator<ContactItem> at.fhooe.kls.ContactItem.CREATOR [static]
Initial value:
= new Parcelable.Creator<ContactItem>() {
        public ContactItem createFromParcel(Parcel in) {
            return new ContactItem(in);
        }
        public ContactItem[] newArray(int size) {
            return new ContactItem[size];
        }
    }
The Constant CREATOR.
Definition at line 124 of file ContactItem.java.
The documentation for this class was generated from the following file:
src/at/fhooe/kls/ContactItem.java