at.fhooe.kls.SMSAdapter Class Reference
Public Member Functions
SMSAdapter open (String password) throws SQLException
boolean isOpen ()
void close ()
long createNote (String email, String key)
String getKey (String email)
Cursor fetchNote (String email) throws SQLException
Static Public Member Functions
static synchronized SMSAdapter getInstance (Context ctx)
Static Public Attributes
static final String PREFS_NAME = `smsadapter`
Protected Member Functions
SMSAdapter (Context ctx)
Detailed Description
The Class SMSAdapter.
Definition at line 18 of file SMSAdapter.java.
Constructor & Destructor Documentation
at.fhooe.kls.SMSAdapter.SMSAdapter (Context ctx) [protected]
Instantiates a new sMS adapter.
Parameters
ctx the ctx
Definition at line 109 of file SMSAdapter.java.
Referenced by at.fhooe.kls.SMSAdapter.getInstance().
Member Function Documentation
void at.fhooe.kls.SMSAdapter.close ()
Close.
Implements at.fhooe.kls.ISMSAdapter.
Definition at line 185 of file SMSAdapter.java.
long at.fhooe.kls.SMSAdapter.createNote (String email, String key)
Creates the note.
Parameters
email the email
key the key
Returns
the long
Implements at.fhooe.kls.ISMSAdapter.
Definition at line 196 of file SMSAdapter.java.
References at.fhooe.kls.Util.encrypt(), at.fhooe.kls.SMSAdapter.getKey(), at.fhooe.kls.Hash.SHA256(), and at.fhooe.kls.Util.toHex().
Cursor at.fhooe.kls.SMSAdapter.fetchNote (String email) throws SQLException
Fetch note.
Parameters
email the email
Returns
the cursor
Exceptions
SQLException the sQL exception
Implements at.fhooe.kls.ISMSAdapter.
Definition at line 257 of file SMSAdapter.java.
Referenced by at.fhooe.kls.SMSAdapter.getKey().
static synchronized SMSAdapter at.fhooe.kls.SMSAdapter.getInstance (Context ctx) [static]
Gets the single instance of SMSAdapter.
Parameters
ctx the ctx
Returns
single instance of SMSAdapter
Definition at line 122 of file SMSAdapter.java.
References at.fhooe.kls.SMSAdapter.SMSAdapter().
String at.fhooe.kls.SMSAdapter.getKey (String email)
Gets the key.
Parameters
email the email
Returns
the key
Implements at.fhooe.kls.ISMSAdapter.
Definition at line 232 of file SMSAdapter.java.
References at.fhooe.kls.Util.decrypt(), at.fhooe.kls.SMSAdapter.fetchNote(), at.fhooe.kls.Hash.SHA256(), and at.fhooe.kls.Util.toByte().
Referenced by at.fhooe.kls.SMSAdapter.createNote().
boolean at.fhooe.kls.SMSAdapter.isOpen ()
Checks if is open.
Returns
true, if is open
Implements at.fhooe.kls.ISMSAdapter.
Definition at line 173 of file SMSAdapter.java.
SMSAdapter at.fhooe.kls.SMSAdapter.open (String password) throws SQLException
Open.
Parameters
password the password
Returns
the sMS adapter
Exceptions
SQLException the sQL exception
Implements at.fhooe.kls.ISMSAdapter.
Definition at line 137 of file SMSAdapter.java.
References at.fhooe.kls.SMSAdapter.PREFS_NAME, at.fhooe.kls.Hash.SHA256(), and at.fhooe.kls.Util.toHex().
Member Data Documentation
final String at.fhooe.kls.SMSAdapter.PREFS_NAME = `smsadapter` [static]
The Constant PREFS_NAME.
Definition at line 21 of file SMSAdapter.java.
Referenced by at.fhooe.kls.SMSAdapter.open().
The documentation for this class was generated from the following file:
src/at/fhooe/kls/SMSAdapter.java