at.fhooe.kls.Chat Class Reference
Public Member Functions
void onCreate (Bundle savedInstanceState)
void onClick (View v)
void setContact (ContactItem _contact)
void chatCreated (org.jivesoftware.smack.Chat arg0, boolean arg1)
Detailed Description
The Class Chat.
Definition at line 27 of file Chat.java.
Member Function Documentation
void at.fhooe.kls.Chat.onCreate (Bundle savedInstanceState)
Called when the activity is first created.
Parameters
savedInstanceState the saved instance state
Definition at line 51 of file Chat.java.
References at.fhooe.kls.XMPPClient.getConnection(), at.fhooe.kls.XMPPClient.getInstance(), and at.fhooe.kls.ContactItem.getUser().
void at.fhooe.kls.Chat.setContact (ContactItem _contact)
Sets the contact.
Parameters
_contact the new contact
Definition at line 136 of file Chat.java.
The documentation for this class was generated from the following file:
src/at/fhooe/kls/Chat.java