at.fhooe.kls.SecureSMSActivity Class Reference
Public Member Functions
void onCreate (Bundle savedInstanceState)
void onActivityResult (int requestCode, int resultCode, Intent intent)
void onClick (View v)
void showQrCode (String data)
void onItemClick (AdapterView<?> parent, View v, int pos, long arg3)
boolean onItemLongClick (AdapterView<?> parent, View v, int pos, long arg3)
void entriesAdded (Collection< String > addresses)
void entriesDeleted (Collection< String > addresses)
void entriesUpdated (Collection< String > addresses)
void presenceChanged (Presence presence)
void chatCreated (org.jivesoftware.smack.Chat chat, boolean createdLocally)
Protected Member Functions
void onDestroy ()
void onResume ()
void onStart ()
void onPause ()
Detailed Description
The Class SecureSMSActivity.
Definition at line 40 of file SecureSMSActivity.java.
Member Function Documentation
void at.fhooe.kls.SecureSMSActivity.onCreate (Bundle savedInstanceState)
Called when the activity is first created.
Parameters
savedInstanceState the saved instance state
Definition at line 78 of file SecureSMSActivity.java.
References at.fhooe.kls.XMPPClient.getInstance(), at.fhooe.kls.XMPPClient.getRoster(), at.fhooe.kls.XMPPClient.isConnected(), at.fhooe.kls.ContactItem.setAvailable(), at.fhooe.kls.ContactItem.setStatus(), and at.fhooe.kls.Util.showToast().
void at.fhooe.kls.SecureSMSActivity.showQrCode (String data)
Show qr code.
Parameters
data the data
Definition at line 256 of file SecureSMSActivity.java.
The documentation for this class was generated from the following file:
src/at/fhooe/kls/SecureSMSActivity.java