XmppGateway Class Reference
Public Member Functions
XmppGateway ()
void initUI ()
void windowClosing (WindowEvent e)
Static Public Member Functions
static void main (String[] args)
Detailed Description
Definition at line 15 of file XmppGateway.java.
Constructor & Destructor Documentation
XmppGateway.XmppGateway ()
Definition at line 18 of file XmppGateway.java.
References initUI().
Referenced by main().
Member Function Documentation
void XmppGateway.initUI ()
Definition at line 23 of file XmppGateway.java.
Referenced by XmppGateway().
static void XmppGateway.main (String[] args) [static]
Parameters
args
Definition at line 40 of file XmppGateway.java.
References XmppGateway().
void XmppGateway.windowClosing (WindowEvent e)
Definition at line 50 of file XmppGateway.java.
References XmppPanel.disconnect().
The documentation for this class was generated from the following file:
src/XmppGateway.java