XmppPanel Class Reference
Public Member Functions
XmppPanel ()
void connect ()
void disconnect ()
void processPacket (Packet _packet)
void printMessage (Message msg)
void handleSIPMessage (String from, String to, String msg)
void connectionClosed ()
void connectionClosedOnError (Exception e)
void reconnectingIn (int arg0)
void reconnectionFailed (Exception arg0)
void reconnectionSuccessful ()
Private Member Functions
void forwardMessage (Message msg)
Private Attributes
HashMap< String, WTFConnection > m_connections = new HashMap<>()
HashMap< String, String > m_accounts = new HashMap<>()
HashMap< String, String > m_relation_in = new HashMap<>()
HashMap< String, String > m_relation_out = new HashMap<>()
JList m_connectionList
JTextArea m_logArea
JScrollPane scrollPane_2
DefaultListModel< WTFConnection > m_listModel
JLabel lblXmppConnections
JLabel label
JLabel label_1
ConnectionConfiguration xmppConfig
ConnectionConfiguration m_config
Static Private Attributes
static final long serialVersionUID = 5657339239939443076L
static final int DELAY = 1000
Detailed Description
The Class XmppPanel.
Definition at line 29 of file XmppPanel.java.
Constructor & Destructor Documentation
XmppPanel.XmppPanel ()
Instantiates a new xmpp panel.
Definition at line 80 of file XmppPanel.java.
References connect(), label, label_1, lblXmppConnections, m_accounts, m_config, m_connectionList, m_listModel, m_logArea, m_relation_in, m_relation_out, and scrollPane_2.
Member Function Documentation
void XmppPanel.connect ()
Connect all the gateway clients
Definition at line 140 of file XmppPanel.java.
References DELAY, m_accounts, m_config, m_connections, and m_listModel.
Referenced by XmppPanel().
void XmppPanel.connectionClosed ()
Definition at line 283 of file XmppPanel.java.
void XmppPanel.connectionClosedOnError (Exception e)
Definition at line 291 of file XmppPanel.java.
void XmppPanel.disconnect ()
Disconnect the gateway clients
Definition at line 190 of file XmppPanel.java.
References m_connections.
Referenced by XmppGateway.windowClosing().
void XmppPanel.forwardMessage (Message msg) [private]
Forward message to SIP
Parameters
msg the msg
Definition at line 223 of file XmppPanel.java.
References Server.handleXMPPMessage(), and m_relation_in.
Referenced by processPacket().
void XmppPanel.handleSIPMessage (String from, String to, String msg)
Handle sip message and forwards it to the xmpp user
Parameters
from the sip user
to the xmpp user
msg the message
Definition at line 255 of file XmppPanel.java.
References m_connections, m_logArea, and m_relation_out.
void XmppPanel.printMessage (Message msg)
Prints the Message on the screen and on the standard output
Parameters
msg the Message which should be printed
Definition at line 234 of file XmppPanel.java.
References m_logArea, and m_relation_in.
Referenced by processPacket().
void XmppPanel.processPacket (Packet _packet)
Definition at line 205 of file XmppPanel.java.
References forwardMessage(), and printMessage().
void XmppPanel.reconnectingIn (int arg0)
Definition at line 299 of file XmppPanel.java.
void XmppPanel.reconnectionFailed (Exception arg0)
Definition at line 307 of file XmppPanel.java.
void XmppPanel.reconnectionSuccessful ()
Definition at line 315 of file XmppPanel.java.
Member Data Documentation
final int XmppPanel.DELAY = 1000 [static], [private]
The Constant DELAY.
Definition at line 75 of file XmppPanel.java.
Referenced by connect().
JLabel XmppPanel.label [private]
The label.
Definition at line 63 of file XmppPanel.java.
Referenced by XmppPanel().
JLabel XmppPanel.label_1 [private]
The label_1.
Definition at line 66 of file XmppPanel.java.
Referenced by XmppPanel().
JLabel XmppPanel.lblXmppConnections [private]
The lbl xmpp connections.
Definition at line 60 of file XmppPanel.java.
Referenced by XmppPanel().
HashMap<String, String> XmppPanel.m_accounts = new HashMap<>() [private]
The m_accounts.
Definition at line 39 of file XmppPanel.java.
Referenced by connect(), and XmppPanel().
ConnectionConfiguration XmppPanel.m_config [private]
The m_config.
Definition at line 72 of file XmppPanel.java.
Referenced by connect(), and XmppPanel().
JList XmppPanel.m_connectionList [private]
The m_connection list.
Definition at line 48 of file XmppPanel.java.
Referenced by XmppPanel().
HashMap<String, WTFConnection> XmppPanel.m_connections = new HashMap<>() [private]
The m_connections.
Definition at line 36 of file XmppPanel.java.
Referenced by connect(), disconnect(), and handleSIPMessage().
DefaultListModel<WTFConnection> XmppPanel.m_listModel [private]
The m_list model.
Definition at line 57 of file XmppPanel.java.
Referenced by connect(), and XmppPanel().
JTextArea XmppPanel.m_logArea [private]
The m_log area.
Definition at line 51 of file XmppPanel.java.
Referenced by handleSIPMessage(), printMessage(), and XmppPanel().
HashMap<String, String> XmppPanel.m_relation_in = new HashMap<>() [private]
The m_relation_in.
Definition at line 42 of file XmppPanel.java.
Referenced by forwardMessage(), printMessage(), and XmppPanel().
HashMap<String, String> XmppPanel.m_relation_out = new HashMap<>() [private]
The m_relation_out.
Definition at line 45 of file XmppPanel.java.
Referenced by handleSIPMessage(), and XmppPanel().
JScrollPane XmppPanel.scrollPane_2 [private]
The scroll pane_2.
Definition at line 54 of file XmppPanel.java.
Referenced by XmppPanel().
final long XmppPanel.serialVersionUID = 5657339239939443076L [static], [private]
The Constant serialVersionUID.
Definition at line 33 of file XmppPanel.java.
ConnectionConfiguration XmppPanel.xmppConfig [private]
The xmpp config.
Definition at line 69 of file XmppPanel.java.
The documentation for this class was generated from the following file:
src/XmppPanel.java